import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {client,demo,dayString} from './client';
import {localInstant} from './scheduler';
import './style.css';
const SITE='https://muhammad-ali-hussain-engineering.muhammadalifarhanhus.chatgpt.site';
const time=n=>new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(n);
const longDay=d=>new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'));
const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
function App(){
 const [events,setEvents]=useState([]),[date,setDate]=useState(dayString()),[title,setTitle]=useState('Project focus session'),[earliest,setEarliest]=useState('09:00'),[latest,setLatest]=useState('17:00'),[duration,setDuration]=useState(60),[slot,setSlot]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deleteId,setDeleteId]=useState(null);
 const requestKey=useRef('');const resultHeading=useRef(null);
 useEffect(()=>{client.list().then(setEvents).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[]);
 const daily=events.filter(e=>dayString(new Date(e.start))===date).sort((a,b)=>a.start-b.start);
 const booked=daily.reduce((sum,e)=>sum+(e.end-e.start)/60000,0);
 function update(setter,value){setter(value);setSlot(null);setError('');setNotice('');}
 async function search(e){e.preventDefault();setBusy(true);setSlot(null);setError('');setNotice('');try{
  const start=localInstant(date,earliest),end=localInstant(date,latest);if(end<=start)throw new Error('The window must end after it starts.');
  const result=await client.suggest(start,end,Number(duration));requestKey.current=crypto.randomUUID();setSlot(result);
  setTimeout(()=>resultHeading.current?.focus(),0);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 async function confirm(){setBusy(true);setError('');try{await client.book(title.trim(),slot,requestKey.current);setSlot(null);setNotice('Event booked. Your agenda has been updated.');setEvents(await client.list());}catch(e){setError(e.message);setSlot(null);}finally{setBusy(false);}}
 async function remove(id){setBusy(true);setError('');try{await client.remove(id);setEvents(await client.list());setSlot(null);setDeleteId(null);setNotice('Event deleted.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function reset(){setBusy(true);try{await client.reset();setEvents(await client.list());setSlot(null);setDate(dayString());setError('');setNotice('Sample agenda restored.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><header><a className="logo" href={SITE}>MH<span>_</span></a><a className="back" href={SITE+'/#work'}>← Engineering portfolio</a><a className="source" href="https://github.com/Muhammad-Ali-Hussain-PRO/Project-3/tree/applied-engineering-upgrade/fullstack" target="_blank" rel="noopener noreferrer">View source ↗</a></header>
 <main><div className="title-row"><div><p className="eyebrow">CHRONOSAI / SCHEDULING WORKSPACE</p><h1>Make room for<br/><em>what comes next.</em></h1></div><div className="mode"><span className="mode-label">{demo?'BROWSER DEMO':'PYTHON API WORKSPACE'}</span><p>{demo?'Changes are saved only in this browser.':'Bookings are saved through the Python API.'}</p><small>Times shown in {zone}</small></div></div>
 <div className="workspace"><section className="request panel" aria-labelledby="request-title"><div className="panel-top"><span>01 / PLAN</span><span aria-hidden="true">+</span></div><h2 id="request-title">Find your next opening.</h2><p className="muted">Choose a window. Review the proposed time before anything is booked.</p>
 <form onSubmit={search}><label htmlFor="title">Event title</label><input id="title" value={title} required maxLength={120} onChange={e=>update(setTitle,e.target.value)} disabled={busy}/><label htmlFor="date">Day</label><input id="date" type="date" required value={date} onChange={e=>update(setDate,e.target.value)} disabled={busy}/><div className="two"><div><label htmlFor="earliest">Earliest start</label><input id="earliest" type="time" required value={earliest} onChange={e=>update(setEarliest,e.target.value)} disabled={busy}/></div><div><label htmlFor="latest">Finish by</label><input id="latest" type="time" required value={latest} onChange={e=>update(setLatest,e.target.value)} disabled={busy}/></div></div><label htmlFor="duration">Duration</label><select id="duration" value={duration} onChange={e=>update(setDuration,Number(e.target.value))} disabled={busy}>{[15,30,45,60,90,120].map(n=><option key={n} value={n}>{n} minutes</option>)}</select><button className="primary" disabled={busy||!title.trim()}>{busy?'Working…':'Find an available time'} <span aria-hidden="true">→</span></button></form>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 </section><section className="agenda panel" aria-labelledby="agenda-title"><div className="panel-top"><span>02 / YOUR DAY</span><span>{daily.length} {daily.length===1?'event':'events'}</span></div><h2 id="agenda-title">{longDay(date)}</h2><p className="muted">{booked} minutes scheduled <span className="sep">/</span> {demo?'Personal demo agenda':'Workspace agenda'}</p><div className="agenda-list" aria-busy={busy}>{daily.length===0?<div className="empty"><span aria-hidden="true">◷</span><h3>A little breathing room.</h3><p>No events on this day. Find a time to add your first one.</p></div>:daily.map(e=><article className="event" key={e.id}><div className="event-time">{time(e.start)}<span>{time(e.end)}</span></div><div className="event-detail"><h3>{e.title}</h3><p>{Math.round((e.end-e.start)/60000)} minutes</p>{deleteId===e.id?<div className="delete-confirm"><span>Delete this event?</span><button disabled={busy} onClick={()=>remove(e.id)}>Delete</button><button onClick={()=>setDeleteId(null)}>Keep</button></div>:<button className="text-button" disabled={busy} onClick={()=>setDeleteId(e.id)} aria-label={'Delete '+e.title}>Delete event</button>}</div></article>)}</div>
 {demo&&<button className="reset" disabled={busy} onClick={reset}>Restore sample agenda</button>}</section>
 <section className={'result panel '+(slot?'ready':'')} aria-labelledby="result-title"><div className="panel-top"><span>03 / REVIEW</span><span>{slot?'READY TO CONFIRM':'AWAITING REQUEST'}</span></div><h2 id="result-title" tabIndex="-1" ref={resultHeading}>{slot?'Your next opening.':'A clear decision.'}</h2>{slot?<><p className="slot-date">{longDay(date)}</p><p className="slot-time">{time(slot.start)}<span>to {time(slot.end)}</span></p><p className="muted">{duration} minutes · {zone}</p><div className="reason"><h3>Why this time?</h3>{slot.conflicts.length?<><p>The requested start overlaps existing events. The search moved past:</p><ul>{slot.conflicts.map((e,i)=><li key={i}>{e.title} <span>{time(e.start)}–{time(e.end)}</span></li>)}</ul></>:<p>Your requested start is free and the event fits inside your window.</p>}<p>Adjacent events can meet at the same boundary.</p></div><button className="primary" onClick={confirm} disabled={busy||!title.trim()}>Confirm booking <span aria-hidden="true">✓</span></button><p className="footnote">Availability is checked again when you confirm.</p></>:<div className="result-empty"><div className="step"><b>1</b><p>Search inside your time window.</p></div><div className="step"><b>2</b><p>See the first available slot and any conflicts.</p></div><div className="step"><b>3</b><p>Confirm when the time works for you.</p></div></div>}</section></div>
 <details className="about"><summary>How this project works</summary><div><p>A deterministic interval scheduler supports preview, confirmation and deletion. The source includes a React interface, a Python FastAPI service, and PostgreSQL storage with scoped workspace tokens and atomic booking checks.</p><p>{demo?'This public version runs the same scheduling rules locally and stores sample events on this device. The Python/PostgreSQL version is provided in the source with setup instructions.':'This version uses the Python service. Tokens identify a private workspace in this prototype; account recovery and external calendar synchronization are future work.'} No external calendar is accessed and no language model is called.</p><a href={SITE+'/portfolio/'}>Read the technical case study ↗</a></div></details>
 </main><footer><span>Built for the engineering portfolio of Muhammad Ali Hussain</span><a href={SITE+'/resume/'}>Resume ↗</a><a href={SITE+'/cv/'}>CV ↗</a></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
